CREATE TABLE test_exists_1 ( a INTEGER );
CREATE TABLE test_exists_2 ( b INTEGER );
INSERT INTO test_exists_1 VALUES (1);
INSERT INTO test_exists_1 VALUES (2);
INSERT INTO test_exists_1 VALUES (3);
INSERT INTO test_exists_1 VALUES (4);
INSERT INTO test_exists_2 VALUES (30);
INSERT INTO test_exists_2 VALUES (40);
INSERT INTO test_exists_2 VALUES (50);
INSERT INTO test_exists_2 VALUES (60);
