INSERT INTO insert_perf VALUES (1, 'uncomelinesses thermoneurosis prerestrict subnubilar argos chordacentrous astrogational sanguisorbaceae gablewise echelonment socdoliger renniogen virtuelessness trichostrongyle daktyl chapah undisper', 58.8389);
INSERT INTO insert_perf VALUES (2, 'seamrog ribbonman trimethylamines dhooley unsavorly cunye iwao unnavigableness overconfiding kitkahaxki arabianize dyakish stilettolike tabbyhoods wantonizes underlift miranha', 95.6221);
INSERT INTO insert_perf VALUES (3, 'hanefiyeh quinoform clubster extrasomatic anatopism unextruded urnmaker draughtswomanship ulmo', 80.7046);
INSERT INTO insert_perf VALUES (4, 'keratometers niccolo needleworked dashnakist vatmaking pharyngotyphoid keratophyr decancellating yahuskin nonequestrian unincensed whippowill', 29.8738);
INSERT INTO insert_perf VALUES (5, 'ankylodontia savablenesses topotypical rhematology levigator', 47.1143);
INSERT INTO insert_perf VALUES (6, 'consperg ruberythrinic cleanhearted obl', 13.5198);
INSERT INTO insert_perf VALUES (7, 'balden anukit subhepatic supralunary sanctorian stratagematic antrotympanic typhlomegaly holcad millioned hygrophthalmic aljamia heartroot eastland aplustria athletas necrophobes', 36.3535);
INSERT INTO insert_perf VALUES (8, 'spasmodism nonsimilarity kharouba cephalophorous figgiest bossa guatuso unmumbling wifelessness nondigestion othelcosis outscour unmouldy pneumonocirrhosis', 60.2969);
INSERT INTO insert_perf VALUES (9, 'molinia filicales lilactide chevance fridila nectron hostlership forwanders tenebrionidae eclectics odax rebewail cornerbind nanander moocha goodlike', 2.65786);
INSERT INTO insert_perf VALUES (10, 'degradingness cadmopone gutrots incongenerous inusitateness taglia skintled spheriform', 34.4226);
INSERT INTO insert_perf VALUES (11, 'immortified englishly cadence sulphouinic spreazes clutchman ticketmonger nonrepublican recivilize nonmarriage squadder', 42.1919);
INSERT INTO insert_perf VALUES (12, 'chrysanisic antihierarchist precollapsibility kechel snodly unscowlingly scandian hammerstone sarex hawiya postclitellian', 12.4243);
INSERT INTO insert_perf VALUES (13, 'nonenteric alditol bevesselled nidularia accelerograph ihs perisphinctoid nonethnical', 96.4494);
INSERT INTO insert_perf VALUES (14, 'naujaite preendorsing irrepatriable unmarled overfaith pseudocolus learnership inorderly cyrtoceras kinker expatiatingly biographed trailery skraelling nereidean appulsive', 12.2154);
INSERT INTO insert_perf VALUES (15, 'nonvexatiously imboscata nicish alloplasmic schechitas hemiholohedral', 87.5366);
INSERT INTO insert_perf VALUES (16, 'hingeways pansphygmograph rhodophyll musculospiral algerite nonvitrified snobbers superrighteous unsourly withturn superindignant barophobia fructuosity milliform introvertish herniopuncture untangent', 55.8076);
INSERT INTO insert_perf VALUES (17, 'afraidness prasine furtum orbitally cantation boilermaking whoobubs shelffellow nontemptation hallowtide pseudandry', 53.2859);
DELETE FROM insert_perf WHERE num >= 39.5758 AND num <= 50.9656;
INSERT INTO insert_perf VALUES (18, 'farawaynesses childridden maurandia belarus polythalamia', 72.31);
INSERT INTO insert_perf VALUES (19, 'nemichthyidae scatterlings thalassiophyte', 76.4552);
INSERT INTO insert_perf VALUES (20, 'paronymies nonnephritic esloined bandolerismo pruinate lucrezia sclerostenosis sternad whiskerlike pitchwork highpockets delabialize styany tetrachloroethane heliopticon mechanalize', 14.1706);
INSERT INTO insert_perf VALUES (21, 'resudation hydronephelite unenunciable', 93.9642);
INSERT INTO insert_perf VALUES (22, 'elburtz phalangeridae renavigate aurantium agritos durandarte apisms prebeloved burgheristh aftergas rabiform hemiachromatopsia luchuan amorphia stownding cldn begob', 95.0853);
INSERT INTO insert_perf VALUES (23, 'takeful smt stonepecker affuse sofane', 49.3816);
INSERT INTO insert_perf VALUES (24, 'eutaxites superwealthy beboss acylamidobenzene miocene terraculture goodfellows hermannia affraps bion', 45.8859);
INSERT INTO insert_perf VALUES (25, 'microbal mastoideosquamous julyflower unkeyed bidings megasynthetic countervolley boldin serbonian bronk embrowd tinerer hypothesi eightling holosaprophyte aphroditous', 57.8271);
INSERT INTO insert_perf VALUES (26, 'outbatting unsurviving gynecomania kiswahili heterakis nonconvertibleness cakchikel redeclined lips kafkaesque weedling cosaque stilette multicollinearity superthoroughness archiblastula planirostrate', 77.056);
DELETE FROM insert_perf WHERE num >= 27.9353 AND num <= 45.0865;
INSERT INTO insert_perf VALUES (27, 'erlander poecilogale diversipedate unperforative hypogenesis consomma prorefugee isoamyl agni nonpendency aswithe feigningly oligospermia gyrostabilized expositoriness nonrefined scrivened dottipoll', 37.7024);
INSERT INTO insert_perf VALUES (28, 'acneform platyhieric chloroanaemia pneumonosis prolling heterochromy fenis revalentas anatomism belltopperdom', 72.4755);
INSERT INTO insert_perf VALUES (29, 'encyclopaedize ivyberries ethnicize hereditarist romulian intermeningeal flashforwarded ragamuffinly misexplained scrunger monodermic crouchingly madderish', 59.7351);
INSERT INTO insert_perf VALUES (30, 'venada olivilin unreducibleness subbrigade fototronic searcer triloculate celiomyalgia unspinsterlike ganocephalous', 61.0468);
INSERT INTO insert_perf VALUES (31, 'coronale eurasians pentit hagiologically deathin', 83.1485);
INSERT INTO insert_perf VALUES (32, 'elmwoods azoxynaphthalene ghrush cabs flandowser overaffirmative vamos shorling squamscot herpetofaunas preimpart tupolev ventriculopuncture gonocoele orthodiazin ephebeia mistrow soapfish unimbittere', 35.9665);
INSERT INTO insert_perf VALUES (33, 'grapeful bsba neti unbudding parietojugal causticized munja', 47.6103);
INSERT INTO insert_perf VALUES (34, 'ferratin bomu viperan elegious postulantship stut', 55.8611);
INSERT INTO insert_perf VALUES (35, 'didactician anaptychi flurred', 67.2143);
INSERT INTO insert_perf VALUES (36, 'overfruitfully exadverso unimprovedly peptonelike jellily palaeichthyological scuddy undecision', 13.0067);
INSERT INTO insert_perf VALUES (37, 'vicegerentship autophonoscope parorchid nonenlightened delegant unimplicable ligamentum unsaltatory undemonstrably coronize teleseismology arzan nonenemy drimys megaseismic disputisoun dillweed unearn', 31.7275);
INSERT INTO insert_perf VALUES (38, 'statary stoorey striplight nondeflected semimetamorphosis victrolla prepractice kesting vad rstse muffledly swimwears staphylomycosis', 96.4912);
INSERT INTO insert_perf VALUES (39, 'chemiotaxis apterygote regrabbed uneditable rowndell unreverence oxyquinone hemianopsias bovensmilde turonian parilicium ronco abiston overpublicity', 93.5294);
INSERT INTO insert_perf VALUES (40, 'douziames propulsors bontoc pretarsus tawt chorioptic turkeyberry soothered alchemistry acheft underbright amylogenic uniangulate pseudoameboid preministry cytopyge lowting aruntas va', 11.7519);
INSERT INTO insert_perf VALUES (41, 'bestorming precony bumbarge scolophore disulphoxide paraquinone gilim', 60.0706);
INSERT INTO insert_perf VALUES (42, 'underedge insusurration spirignath', 33.9594);
INSERT INTO insert_perf VALUES (43, 'unbarbarising epistemonic frequentable pygmalionism blewarts medallioning gasteromycete hypobasis appius paralaurionite hellim bewaitered unhallucinating', 94.5785);
INSERT INTO insert_perf VALUES (44, 'schnozzola purpie larentalia rcl nonpreferableness cycloidean andorre tamenes abedge ringcraft nagaris threip', 89.8891);
INSERT INTO insert_perf VALUES (45, 'ubiquist overaccentuation fleshhoods trusix aspca fersmite mime amphimictically sphaeropsidales helianthin physopodan undisciplines admonitrix pailoo wusser hyperdiploid', 47.643);
INSERT INTO insert_perf VALUES (46, 'ornithurous bacheller munificentness phacochoeroid crustosis tonsilitises', 20.6432);
INSERT INTO insert_perf VALUES (47, 'corruptedness cartware floeberg peptonizer apotactite oilstock hagia quinolinium mannerise nimbated balinghasay bribetaking unfulminated hartke', 71.5798);
INSERT INTO insert_perf VALUES (48, 'riia varsha incretionary chamomilla subqualities typhula sebastodes kamao mackaybean enteropneustan ungastric', 50.6953);
INSERT INTO insert_perf VALUES (49, 'sicani highlandry alumite firks underteacher exsequatur yokkaichi ovalisation mommer undancing adversifolious descriptionist idiasm megalocephalia angild talotibial citharoedus rudulph', 52.1512);
INSERT INTO insert_perf VALUES (50, 'nonvindication unpenitentness corelational noneugenically echinocaris polymelia syll unvouchedness macabresque coles unwonderfully organoid retrahent pondo selly scarplet gryding nautiloidean evelynne', 93.5176);
INSERT INTO insert_perf VALUES (51, 'uncreatability insubvertible immunol ssu rewhiten hedgebreaker anematized defunctionalization antilaborist betis unchinked athyrid asexualising kwintra nonorthographical stenia', 64.8025);
INSERT INTO insert_perf VALUES (52, 'unchildish urofuscohematin portraited engrafter heho intertone sabalo nongerminal unecclesiastic terraquedus predisagree mirdaha underback demihigh bitterbump incrystallizable encharming isopyrum assa', 35.8814);
INSERT INTO insert_perf VALUES (53, 'scirrhusses nonenviousness theromorphology', 94.1671);
INSERT INTO insert_perf VALUES (54, 'nonperceiving mephistophelean tulkepaia deckswabber usipetes snortle pretersensual', 68.0695);
INSERT INTO insert_perf VALUES (55, 'hairmoneering deindividualization limnos beshake anidian bonnive', 85.7891);
INSERT INTO insert_perf VALUES (56, 'epiphanised utilitarianist outquestion megalodontia periorbita boucl macroflora cowardries interblended sanggau artifex prebalanced', 39.3539);
INSERT INTO insert_perf VALUES (57, 'laryngostroboscope phersephatta befrocked pantodon unenhanced unanarchistic undelusiveness deltohedra', 95.4094);
INSERT INTO insert_perf VALUES (58, 'tarnkappe adless dihelios embathed threapen bravuraish overfloridly murmurless antimartyr daphni', 51.9531);
DELETE FROM insert_perf WHERE num >= 29.1425 AND num <= 71.7589;
INSERT INTO insert_perf VALUES (59, 'unwry unodiousness trilliaceae zonociliate hemicircle noncoercively unsubserviently disney filemark udaler seemlyheds critch hematoclasis unnilquintium femicide rufoferruginous liquifiers thoroughfoot', 99.9392);
INSERT INTO insert_perf VALUES (60, 'hyed hungeringly fatigated wellmen untangental unblighted ultracomplex maladventure yaunde decnet resave jizyah indicatrix ascus', 39.4407);
INSERT INTO insert_perf VALUES (61, 'preadvertent helvine placablenesses daedalidae rematerialization sensomobile infrequentcy hyalopterous gangwayed curtainwise braye plumlet northen desesperance achinese bowla concerningly jaspilite', 24.4993);
INSERT INTO insert_perf VALUES (62, 'thwarteous homoiousious vassalizing msba foresummer erythroderma cosmeses', 95.0589);
INSERT INTO insert_perf VALUES (63, 'caseconv blocklike greekise aloelike ceratomandibular universologist crotalus hallier imperspirability', 43.0944);
INSERT INTO insert_perf VALUES (64, 'angelot sarcophagine unagilely', 97.403);
INSERT INTO insert_perf VALUES (65, 'sandbin erugation shastracara shkupetar dolmetsch kadein dmitrevsk omnisufficiency ethercap stc chicker unfrenzied palaeocrystalline nammo', 98.3381);
INSERT INTO insert_perf VALUES (66, 'ligniferous wordsmanship parishional mikie microdose typotelegraphy khuen hemiopias ethicophysical undisagreeable', 47.84);
DELETE FROM insert_perf WHERE num >= 10.916 AND num <= 95.7428;
INSERT INTO insert_perf VALUES (67, 'repercussiveness leucaniline synapsidan myrrhophore propupal peritreme', 24.1209);
INSERT INTO insert_perf VALUES (68, 'argillous catholyte duodynatron', 18.582);
INSERT INTO insert_perf VALUES (69, 'wosome igbira foolhardises trainboy thermocoagulation strone lozens bryophyllum promic mutulary engregge', 64.5203);
INSERT INTO insert_perf VALUES (70, 'athel lashness betrail areothofs teathe mashru pseudosiphonal caprizant speight', 53.5345);
INSERT INTO insert_perf VALUES (71, 'euxanthate sauf metaplumbate raghouse churchisms unfundable unbarrenly thunderful sartage ktu surquidry archheart', 93.6761);
INSERT INTO insert_perf VALUES (72, 'overbow quinatoxin moosecall crudelity', 65.2927);
INSERT INTO insert_perf VALUES (73, 'stauracin nonapposable peptical subtranslucency calistheneum unornamentation georgesman', 33.0868);
INSERT INTO insert_perf VALUES (74, 'pleurocele elasticnesses cosmozoism femorofibular oesophagism amphioxidae cardioplegia foredecree lymantriidae pseudotetrameral monogrammatical malmed mugiloid unembroiled archbp overharshly semipapis', 7.09653);
INSERT INTO insert_perf VALUES (75, 'lesleya hysterophyta gesticularious adjoiningness membraniform unbetrothed superendorse', 38.4056);
INSERT INTO insert_perf VALUES (76, 'parliamentarisms verticilliosis hyssopus somatization diagrammatize chinnam katabolize brineless foreimpressed unsarcastic', 33.9285);
INSERT INTO insert_perf VALUES (77, 'knox jonvalize dennstaedtia furcilia scamillus unadmiringly caccini arumin zulinde vcci prenative pulsatilla preflattery extratemporal semifriable', 50.5336);
INSERT INTO insert_perf VALUES (78, 'polyspored daincha pmc ganoblast oophoromania', 67.9702);
INSERT INTO insert_perf VALUES (79, 'schemist cretize dobuan paragraphize charact thicking uvver regush superadmiration knitback calorify ethenol daviesia eltrot poecilocyttarous', 74.8258);
INSERT INTO insert_perf VALUES (80, 'borzicactus eisa hebrewdom decrepitnesses urethylane caitives lamut underwinding', 26.6204);
INSERT INTO insert_perf VALUES (81, 'chapacura demonologer cholo signficances ladylikely coroplast pouldre antipyrin owergang', 57.5249);
INSERT INTO insert_perf VALUES (82, 'jic enravishment unsophomorical resinic akhziv antilaborist cringingness ferrash undercoachmen synchytriaceae iatrogenies unshadiness frostwort aih noncredent jumboesque platformistic preeffective har', 22.8498);
INSERT INTO insert_perf VALUES (83, 'sulphimide cicrumspections knitback moschine carangin underruler dhauri keraunophobia xylosma svelt terrigene horsebrier adnephrine jajapura aind inelastically sulaba incarnalised unforecasted', 55.3067);
INSERT INTO insert_perf VALUES (84, 'autodecremented pretention irreclaimed anticontagious vampyrellidae', 62.1127);
INSERT INTO insert_perf VALUES (85, 'roccellin anglehook seborrhoic snobber multicoil unbragged plebiscitic', 73.2954);
INSERT INTO insert_perf VALUES (86, 'sucklebush pyropen forthbringer antipolo illmanneredness pepperish renomme incrementals fadeev onychosis ghizite prepreparation', 35.2525);
INSERT INTO insert_perf VALUES (87, 'pathobiologist arsenicate kistiakowsky lurves unenduringly unseeingness zygnemales basilidianism parapleurum multidenominational superobjectionable serjania wattis archimperialist countermessage earcl', 79.2794);
INSERT INTO insert_perf VALUES (88, 'mbunda doliolum preexchanging cedreatis propionibacterium hastiform disavouch oaklet randomish glycerogelatin entozoological wistit balnea unordinate sethead ditrocha retroactionary beslavered uncogno', 41.5936);
DELETE FROM insert_perf WHERE num >= 67.9154 AND num <= 95.0101;
INSERT INTO insert_perf VALUES (89, 'oxhorn prooflessly adipsia sulfamethazine archcriminal plainswoman faade roudas mizoguchi aureal gratten ailuro', 66.2433);
INSERT INTO insert_perf VALUES (90, 'preimpair masc overdenunciation myrmekite disaccustomedness warehouseage plackart lateropulsion waibling cheiropod sternocleidomastoid underdive dripproof superenthusiastic tacticities birdikin newspa', 67.2516);
INSERT INTO insert_perf VALUES (91, 'nonpropitiative nonelaborateness upttore hemicerebrum dustwoman dodgeful ectolecithal millionist electrodialitic', 65.6833);
INSERT INTO insert_perf VALUES (92, 'nonimpulsiveness dairylea unhearty nonidyllically pantophile mormoness tripinnatifid janus upwhelm montserrat hypophamine', 28.9424);
INSERT INTO insert_perf VALUES (93, 'unnationalized birdweed vanille pabulation pratey thymicolymphatic enzymosis drerihead authotype semiappressed alizarate polycotyly pardhan blepharorrhaphy perisphinctidae joviniamish mfr gutti', 0.580599);
INSERT INTO insert_perf VALUES (94, 'desmodactyli gaggery stubornly phonoplex superempirical shukria', 23.3684);
INSERT INTO insert_perf VALUES (95, 'leatherware firesider lernean punction vagituses regimentaled bribri monodromy similors unviolableness antikinase hopkinsian overleathers ele imbosses fastidiosity gaddang dreamwhiles', 48.9825);
INSERT INTO insert_perf VALUES (96, 'disdodecahedroid tarsoplasty unsensuously postscenia dentimeter adams impsonites nonhydrolysable outhymn erythrocytorrhexis unnegotiated unbevelled furnitureless unpurgative nonclyclical uratosis cuny', 62.4757);
INSERT INTO insert_perf VALUES (97, 'autosensitized cistophori gpi eulysite', 8.68235);
INSERT INTO insert_perf VALUES (98, 'autosite tarantaraing fydorova hypothetist displenishments antemask halysites openendedness defibrillatory uterocele oryctologies', 92.871);
INSERT INTO insert_perf VALUES (99, 'bronchiostenosis nsap yunca superchemical impedible phyllodoce auster lexological', 44.3017);
INSERT INTO insert_perf VALUES (100, 'stylommatophorous circumvest ileitis protomagnesium', 82.1297);

SHOW STORAGE STATS;
EXIT;

