DROP TABLE IF EXISTS test_sj_t1;
DROP TABLE IF EXISTS test_sj_t2;
DROP TABLE IF EXISTS test_sj_t3;
DROP TABLE IF EXISTS test_sj_t4;
DROP TABLE IF EXISTS test_sj_t5;
DROP TABLE IF EXISTS test_sj_t6;
DROP TABLE IF EXISTS test_empty1;
DROP TABLE IF EXISTS test_empty2;
