#!/bin/bash

rm -r datafiles/
./nanodb < schemas/writeahead/create_t.sql > /dev/null

./nanodb < schemas/writeahead/transaction1.sql > scripts/output/t1.out &
./nanodb < schemas/writeahead/transaction2.sql > scripts/output/t2.out
./nanodb < schemas/writeahead/read_t.sql | grep -v "main" | grep '+\||' > scripts/output/undo-parallel.out

if [ -z $(diff scripts/output/undo-parallel.out scripts/output/undo-parallel.expected) ] 
then
    echo "Test undo-parallel passed!"
else
    echo "Test undo-parallel FAILED."
fi
